services:
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    ports: 
      - '5672:5672' 
      - '15672:15672' 
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      # Persist RabbitMQ data
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - network
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_stomp &&
        rabbitmq-server
      "
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3
  mysql:  
    image: mysql:8.0 
    environment:
      MYSQL_DATABASE: 'db'  
      MYSQL_ROOT_PASSWORD: 'password'
    ports: 
      - '3309:3306'
    expose: 
      - '3309' 
    networks:
      - network
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  lunch-backend:
    build:
      context: ./lunch 
    env_file: "./lunch/.env"
    ports:
      - "8081:8081"
    depends_on:
      mysql:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
    networks:
      - network
  lunch-frontend:
    build:
      context: ./restaurant-picker-frontend 
    ports:
      - "80:80"
    depends_on:
      - lunch-backend
      - rabbitmq 
    networks:
      - network
networks:
  network:
    driver: bridge
volumes:
  rabbitmq_data:
    driver: local

